### ISSUE TITLE
Rconsle not working on macOS

### ISSUE THREAD

**Issue by The-Nyla** [TheDutchMC/rConsole#1]
I'm not sure what happens, but both the browser and console show these errors:

![image](https://user-images.githubusercontent.com/79489385/116121812-fcb1a700-a68e-11eb-813f-5da6cb577573.png)

![image](https://user-images.githubusercontent.com/79489385/116121840-076c3c00-a68f-11eb-8f1a-aa3ab3707f7f.png)

and I also tried using chrome in case safari was the problem, but I also get a slightly different error:

![image](https://user-images.githubusercontent.com/79489385/116121988-31bdf980-a68f-11eb-919b-f37fa5f30d15.png)

![image](https://user-images.githubusercontent.com/79489385/116122026-3e425200-a68f-11eb-90d1-083799c730e5.png)

**Comment by TobiasDeBruijn** [comment]
Hey there. Thanks for opening this issue!

You're trying to connect to the TCP Server, which by default listens on port 8080. It doesn't support HTTP, which is what your browser uses.

You'll want to connect to (by default) port 8090, which is where the plugin is listening for HTTP connections, and where you'll find the console!

**Comment by The-Nyla** [comment]
Thanks! it works perfectly now!
